/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import dev.langchain4j.model.chat.ChatLanguageModel
import dev.langchain4j.model.ollama.OllamaChatModel

fun main() {
    val chatModel: ChatLanguageModel = OllamaChatModel.builder()
        .baseUrl("http://192.168.1.248:11434")
        .modelName("deepseek-r1:1.5b")
        .logRequests(true)
        .build()
    println(chatModel.chat("Hello, how are you?"))
}
